=== wushengda/java/basic/WhatHavaToRemember/src/xml/schema/asia.xsd
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="www.asiainfo.com">

<xs:element name="asiainfo">
 <xs:complexType>
 
  <xs:sequence>
   <xs:element name="namespace" type="xs:string"/>
   
   <xs:element name="person-info">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="country" type="xs:string"/>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
   
   <xs:element name="job">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="language" type="xs:string"/>
      <xs:element name="work-year" type="xs:positiveInteger"/>
      <xs:element name="payment" type="xs:decimal"/>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
   
   <xs:element maxOccurs="unbounded" name="love">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="introduce" type="xs:string"/>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
   
  </xs:sequence>
  
  <xs:attribute name="nickName" type="xs:string" use="required"/>
  
 </xs:complexType>
</xs:element>

</xs:schema>

=== wushengda/java/basic/WhatHavaToRemember/bin/xml/schema/asia.xml
<?xml version="1.0" encoding="utf-8"?>
<asiainfo xmlns="www.asiainfo.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.asiainfo.com asia.xsd" nickName="AsiaData">
	
	<namespace>AsiaInfo</namespace>
	
	<person-info>
		<name>邬胜达</name>
		<address>岳麓区中电软件园7号栋亚信数据</address>
		<city>湖南长沙</city>
		<country>中国</country>
	</person-info>
	
	<job>
		<name>软件开发工程师</name>
		<language>Java</language>
		<work-year>2</work-year>
		<payment>1000000</payment>
	</job>
	
	<love>
		<name>编程</name>
		<introduce>用来挣钱的啊</introduce>
	</love>
	
	<love>
		<name>打代码</name>
		<introduce>用来挣钱的啊</introduce>
	</love>
	
	
</asiainfo>
